/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job.testing;

import front.desk.*;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class register extends javax.swing.JFrame {
    
    ResultSet rs = null;
    Connection conn;
    Statement stmt = null;
    PreparedStatement pst = null;
    byte[] pic = null;
    
    public register() {
        initComponents();
        setLocationRelativeTo(null);
        lbl1.setVisible(false);
        lbl2.setVisible(false);
    }
    String ImgPath;
    
    public boolean checkInputs() {
        if (cname.getText() == null
                || caddress.getText() == null
                || cnature.getSelectedItem().toString().equals("")
                || ownertype.getSelectedItem().toString().equals("")
                || website.getText() == null
                || contact.getText() == null
                || mobile.getText() == null
                || email.getText() == null
                || optemail.getText() == null
                || reemail.getText() == null
                || username.getText() == null
                || password.getText() == null
                || repassword.getPassword() == null
                || paths.getText() == null) {
            return false;
        } else {
            try {
                return true;
            } catch (Exception e) {
                
            }
        }
        return false;
    }
    
    public ImageIcon ResizeImage(String imagepath, byte[] pic) {
        ImageIcon myImage = null;
        if (imagepath != null) {
            myImage = new ImageIcon(imagepath);
        } else {
            myImage = new ImageIcon(pic);
            
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cname = new javax.swing.JTextField();
        caddress = new javax.swing.JTextField();
        website = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        office = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        reemail = new javax.swing.JTextField();
        optemail = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        ownertype = new javax.swing.JComboBox<>();
        cnature = new javax.swing.JComboBox<>();
        attach = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SignUp = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        paths = new javax.swing.JTextField();
        txtsearch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        repassword = new javax.swing.JPasswordField();
        password = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        cname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cname.setText("Company Name");
        cname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnameFocusGained(evt);
            }
        });
        cname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnameMouseClicked(evt);
            }
        });
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });

        caddress.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        caddress.setText("Company Address");
        caddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caddressMouseClicked(evt);
            }
        });

        website.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        website.setText("Website");
        website.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                websiteMouseClicked(evt);
            }
        });
        website.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                websiteActionPerformed(evt);
            }
        });

        contact.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        contact.setText("Contact person");
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
        });

        office.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        office.setText("Office Contact");
        office.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                officeMouseClicked(evt);
            }
        });

        mobile.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mobile.setText("Mobile");
        mobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobileMouseClicked(evt);
            }
        });
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        email.setText("Email");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });

        reemail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        reemail.setText("Re-email");
        reemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reemailMouseClicked(evt);
            }
        });
        reemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reemailKeyReleased(evt);
            }
        });

        optemail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        optemail.setText("Opt Email");
        optemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optemailMouseClicked(evt);
            }
        });

        username.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        username.setText("Username");
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        ownertype.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        ownertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ownership Type ", "Governmental ", "Private", "NGOs", "INGOs" }));
        ownertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownertypeActionPerformed(evt);
            }
        });

        cnature.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cnature.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Company Nature", "Accounting\\Finance", "Adviser/Counseling", "Aerospace/Defense", "Automobiles and Parts", "Bank/Financial Institution", "Biotechnology", "Chemicals", "Church/Religious Organization", "Community Organization", "Computers/Technology", "Construction/Engineering/Architects", "Consulting /Legal", "Consulting/Business Services", "Creative / Graphics / Designing", "Data Base Management", "Editor/Copywriter/Writer", "Education", "Energy/Utility", "Engineering/Construction", "Entertainment", "Farming/Agriculture", "FMCG", "Food/Beverages", "Foreign Government Organization", "General Mgmt. / Administration", "Government Organization", "Grocery", "Health/Beauty", "Health/Medical/Pharmaceuticals", "Health/Pharma/Biotech/Medical/R&D", "Hospital / Clinic / Diagnostic Centre", "Hospitality", "Human Resource /Org.Development", "IELTS / TOEFL Instructor", "Industrials", "Insurance Company", "Internet/Software", "Interpreter/ Translator", "IT&Telecommunation", "Legal/Law", "Logistic/Procurement", "Marketing/Advertising/Customer Ser..", "Media/News/Publishing", "Mining/Materials", "NGO/INGO/Social/Develop.Projects", "Non-Profit Organization", "Online Marketing/Advertising", "Others", "Oversees Company", "Pharmaceutical", "Political Organization", "Production/Maintance /Quality", "Retail and Consumer Merchandise", "Sales/Business Development", "School/College", "Secretarial/Front Desk/Receptionist", "Small Business", "Telecommunication", "Transport/Freight", "Travel/Leisure", "University" }));
        cnature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnatureActionPerformed(evt);
            }
        });

        attach.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        attach.setText("Attach");
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Company Logo");

        SignUp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });

        lbl1.setText("*Password is wrong");

        lbl2.setText("* email is wrong!");

        lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("Upload Photo");

        paths.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        paths.setText("Path");
        paths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathsActionPerformed(evt);
            }
        });

        txtsearch.setText("Search");
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtsearchMouseExited(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        repassword.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        repassword.setText("jPasswordField1");
        repassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repasswordActionPerformed(evt);
            }
        });
        repassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                repasswordKeyReleased(evt);
            }
        });

        password.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        password.setText("Password");

        jPanel2.setBackground(new java.awt.Color(0, 191, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 20)); // NOI18N
        jLabel1.setText("Company Register");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addGap(95, 95, 95)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(caddress, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cnature, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(ownertype, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(website, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(reemail, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(optemail, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(repassword, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paths, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(attach, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnature, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownertype, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(website, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(office, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reemail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lbl2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optemail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(paths, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(attach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(SignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ownertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownertypeActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        if (checkInputs() && ImgPath != null) {
            conn = MyConnection.getConnect();
            System.out.println("getc");
            try {
                InputStream img = new FileInputStream(new File(ImgPath));
                String sql = "INSERT INTO `regg`(`cname`, `caddress`, `cnature`, `ownership`, `website`, `contactp`, `officeph`, `mobile`, `email`, `oemail`, `username`, `password`, `logo`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, cname.getText());
                pst.setString(2, caddress.getText());
                pst.setString(3, (String) cnature.getSelectedItem());
                pst.setString(4, (String) ownertype.getSelectedItem());
                pst.setString(5, website.getText());
                pst.setString(6, contact.getText());
                pst.setString(7, office.getText());
                pst.setString(8, mobile.getText());
                pst.setString(9, email.getText());
                pst.setString(10, optemail.getText());
                pst.setString(11, username.getText());
                pst.setString(12, password.getText());
                pst.setBlob(13, img);
                System.out.println("job.chaiyo.register.SignUpActionPerformed()");
                pst.executeQuery();
                System.out.println("success");
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "One or more field is empty", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SignUpActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void websiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_websiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_websiteActionPerformed

    private void cnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnameFocusGained
        // cname.setText(null);
    }//GEN-LAST:event_cnameFocusGained

    private void cnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnameMouseClicked
        cname.setText(null);
    }//GEN-LAST:event_cnameMouseClicked

    private void caddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caddressMouseClicked
        caddress.setText(null);
    }//GEN-LAST:event_caddressMouseClicked

    private void websiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_websiteMouseClicked
        website.setText(null);
    }//GEN-LAST:event_websiteMouseClicked

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        contact.setText(null);
    }//GEN-LAST:event_contactMouseClicked

    private void officeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_officeMouseClicked
        office.setText(null);
    }//GEN-LAST:event_officeMouseClicked

    private void mobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileMouseClicked
        mobile.setText(null);
    }//GEN-LAST:event_mobileMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        email.setText(null);  // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseClicked

    private void reemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reemailMouseClicked
        reemail.setText(null);
    }//GEN-LAST:event_reemailMouseClicked

    private void optemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optemailMouseClicked
        optemail.setText(null);
    }//GEN-LAST:event_optemailMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        username.setText(null);
    }//GEN-LAST:event_usernameMouseClicked

    private void reemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reemailKeyReleased
        if (!email.getText().equals(reemail.getText())) {
            lbl2.setVisible(true);
        } else {
            lbl2.setVisible(false);
        }
    }//GEN-LAST:event_reemailKeyReleased

    private void cnatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnatureActionPerformed
        // TODO add your handling code here:
//        cnature c = evt.getSource();
//        String nature = c.getSeletedItem();
    }//GEN-LAST:event_cnatureActionPerformed

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.img", "*.png", "*.jpg");
        file.addChoosableFileFilter(filter);
        
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl.setIcon(ResizeImage(path, null));
            ImgPath = path;
            paths.setText(ImgPath);
            
        } else {
            JOptionPane.showMessageDialog(null, "No file Selected");
        }
    }//GEN-LAST:event_attachActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        conn = MyConnection.getConnect();
        System.out.println("connnection");
        try {
            String sql = "select * from regg where cname=?";
            pst = conn.prepareStatement(sql);
            System.out.println("inside try");
            
            pst.setString(1, cname.getText());
            System.out.println(cname.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                String coname = rs.getString("cname");
                cname.setText(coname);
                System.out.println(cname.getText());
                String CompanyaAddress = rs.getString("caddress");
                caddress.setText(CompanyaAddress);
                System.out.println(caddress.getText());

//                String CompanyNature=rs.getString("cnature");
//                cnature.setSelectedItem(CompanyNature);
//                
//                String OwnerType=rs.getString("ownership");
//                ownertype.setSelectedItem(OwnerType);
                String CompanyWebsite = rs.getString("website");
                website.setText(CompanyWebsite);
                System.out.println(website.getText());
                String ContactP = rs.getString("contactp");
                contact.setText(ContactP);
                System.out.println(contact.getText());
                String OfficePh = rs.getString("officeph");
                office.setText(OfficePh);
                System.out.println(office.getText());
                
                String Pmobile = rs.getString("mobile");
                mobile.setText(Pmobile);
                System.out.println(mobile.getText());
                String Oemail = rs.getString("email");
                email.setText(Oemail);
                System.out.println(email.getText());
                String Ouser = rs.getString("username");
                username.setText(Ouser);
                
                String Opassword = rs.getString("password");
                password.setText(Opassword);
                System.out.println(password.getText());
                
                pic = rs.getBytes("logo");
                lbl.setIcon(ResizeImage(null, pic));
                System.out.println("lOgo");
                System.out.println("last one");
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_searchActionPerformed

    private void repasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repasswordActionPerformed

    private void repasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repasswordKeyReleased
//        if(!password.getPassword().equals(repassword.getPassword())){
//         lbl1.setVisible(true);
//        }
//        else
//        {
//            lbl1.setVisible(false);
//        }
    }//GEN-LAST:event_repasswordKeyReleased

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void pathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathsActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed

    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
        txtsearch.setText(null);
    }//GEN-LAST:event_txtsearchMouseClicked

    private void txtsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseExited

    }//GEN-LAST:event_txtsearchMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        txtsearch.setText("search");
        cname.setText("Company Name");
        caddress.setText("Company Address");
        website.setText("Website");
        contact.setText("Contact Person");
        office.setText("Office Contact");
        mobile.setText("Mobile");
        email.setText("Email");
        reemail.setText("Re-Email");
        optemail.setText("Opt. Email");
        username.setText("Username");
        password.setText("Password");
        repassword.setText("Confirm Password");
        cnature.setSelectedIndex(0);
        ownertype.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUp;
    private javax.swing.JButton attach;
    private javax.swing.JTextField caddress;
    private javax.swing.JTextField cname;
    private javax.swing.JComboBox<String> cnature;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField office;
    private javax.swing.JTextField optemail;
    private javax.swing.JComboBox<String> ownertype;
    private javax.swing.JTextField password;
    private javax.swing.JTextField paths;
    private javax.swing.JTextField reemail;
    private javax.swing.JPasswordField repassword;
    private javax.swing.JButton search;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField username;
    private javax.swing.JTextField website;
    // End of variables declaration//GEN-END:variables
}
