package front.desk;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Reg extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String Gen;
    byte[] pic = null;
    String filepath;

    public Reg() {
        initComponents();
        setResizable(false);
        txtDapp.setDate(Calendar.getInstance().getTime());
        setLocationRelativeTo(null);
    }
    String ImgPath = null;

    public ImageIcon ResizeImage(String imagepath, byte[] pic) {
        ImageIcon myImage;
        if (imagepath != null) {
            myImage = new ImageIcon(imagepath);
        } else {
            myImage = new ImageIcon(pic);

        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    public boolean checkEmail() {
        if (!(Pattern.matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$", txtEmail.getText()))) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Email address", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    public void Clear() {
        //txtDapp.setDate(null);
        txtFname.setText(null);
        txtLname.setText(null);
        txtCadd.setText(null);
        txtPadd.setText(null);
        txtDob.setDate(null);
        txtNationality.setText(null);
        txtTeleph.setText(null);
        txtMob.setText(null);
        txtGovid.setText(null);
        txtClg1.setText(null);
        txtSem1.setText(null);
        txtStatus1.setText(null);
        txtDiv1.setText(null);
        txtBoard1.setText(null);
        txtSkill.setText(null);
        txtEmail.setText(null);
        radioMale.setSelected(false);
        radiofemale.setSelected(false);
        lblimage.setIcon(null);
        txtJob.setText(null);
        txtSalary.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGen = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radiofemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtGovid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        btnAttachFile = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtClg1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtCadd = new javax.swing.JTextField();
        txtSem1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStatus1 = new javax.swing.JTextField();
        txtPadd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDiv1 = new javax.swing.JTextField();
        txtNationality = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMob = new javax.swing.JTextField();
        txtBoard1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTeleph = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSkill = new javax.swing.JTextField();
        txtDapp = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtDob = new com.toedter.calendar.JDateChooser();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtJob = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGen.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGen.setText("Gender :");
        getContentPane().add(btnGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 101, 25));

        jLabel4.setBackground(new java.awt.Color(0, 102, 204));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Job Details");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 320, -1));

        radioMale.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        radioMale.setText("Male");
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });
        getContentPane().add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 66, -1));

        radiofemale.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        radiofemale.setText("Female");
        radiofemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiofemaleActionPerformed(evt);
            }
        });
        getContentPane().add(radiofemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 85, -1));

        jLabel5.setBackground(new java.awt.Color(0, 102, 204));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("                           Education");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 320, -1));
        getContentPane().add(txtGovid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 275, 29));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setText("Gov. Issued Id No :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 118, -1));

        lblimage.setBackground(new java.awt.Color(255, 255, 255));
        lblimage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        lblimage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblimage.setOpaque(true);
        getContentPane().add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 134, 120));

        btnAttachFile.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAttachFile.setText("Attach Photo");
        btnAttachFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnAttachFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setText("College/Institute*");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 118, 24));
        getContentPane().add(txtClg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 191, 29));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setText("Year/Semester*");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 110, 24));
        getContentPane().add(txtCadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 274, 29));
        getContentPane().add(txtSem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 125, 29));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText("Date of Birth :*");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 82, 27));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setText("Status*");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 64, 24));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Permanent Address :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 141, 24));
        getContentPane().add(txtStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 110, 29));
        getContentPane().add(txtPadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 274, 29));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setText("Division/Rank*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 89, 24));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("Nationality :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 79, 25));
        getContentPane().add(txtDiv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 125, 29));

        txtNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalityActionPerformed(evt);
            }
        });
        getContentPane().add(txtNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 258, 29));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setText("Board/University*");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 118, 24));

        txtMob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobKeyTyped(evt);
            }
        });
        getContentPane().add(txtMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 258, 29));

        txtBoard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoard1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBoard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 231, 29));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Mobile :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 71, 20));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setText("Other Skills :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 118, 24));

        txtTeleph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelephKeyTyped(evt);
            }
        });
        getContentPane().add(txtTeleph, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 274, 29));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Telephone(Landline) :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 25));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 444, 35));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("Date of Application:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 121, 20));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setText("First Name :*");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 141, 23));

        txtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 274, 29));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Last  Name :*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 79, 21));

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 258, 29));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Contact Address :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 28));
        getContentPane().add(txtSkill, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 310, 29));

        txtDapp.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 179, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("Email :*");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 101, 23));

        txtDob.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 258, 29));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 274, 29));

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("                      Personal Information");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 330, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 125, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel24.setText("Job Preferences :");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 118, 24));
        getContentPane().add(txtJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 310, 29));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setText("Expected Salary :");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 118, 24));

        txtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalaryKeyTyped(evt);
            }
        });
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 310, 29));

        jButton1.setText("Attach CV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 660, -1, -1));
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 240, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed
        // TODO add your handling code here:
        Gen = "Male";
    }//GEN-LAST:event_radioMaleActionPerformed

    private void radiofemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiofemaleActionPerformed
        // TODO add your handling code here:
        Gen = "Female";
    }//GEN-LAST:event_radiofemaleActionPerformed

    private void btnAttachFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachFileActionPerformed
        // Image File Chooser:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.img", "*.png", "*.jpg");
        file.addChoosableFileFilter(filter);

        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lblimage.setIcon(ResizeImage(path, null));
            ImgPath = path;
        } else {
            JOptionPane.showMessageDialog(null, "No file Selected");
        }
    }//GEN-LAST:event_btnAttachFileActionPerformed

    private void txtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalityActionPerformed

    private void txtMobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobKeyTyped
        // Only takes number in textfield:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMobKeyTyped

    private void txtBoard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoard1ActionPerformed

    private void txtTelephKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTelephKeyTyped

    private void txtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnameActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
        //checkEmail();
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        //checkEmail();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            con = MyConnection.getconnect();
            String sql = "INSERT INTO `register`(`Date`, `Fname`, `Lname`, `Cadd`, `Padd`, `Dob`, `Nationality`, `Teleph`, `Mob`,`Email`, `Gender`, `Govid`, `Clg`, `Sem`, `Status`, `Divi`, `Board`, `Skill`, `Job`, `Salary`, `image`,cv) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(sql);
            InputStream imgg = new FileInputStream(new File(ImgPath));
//            InputStream pdf = new FileInputStream(new File(filepath));
            File file = new File("C:\\Users\\sawrose\\Documents\\NetBeansProjects\\Job Chaiyo\\Document\\" + docName);

            InputStream in = new FileInputStream(path);
            OutputStream out = new FileOutputStream(file);
            byte[] buffer = new byte[1024];
            int length;

            while ((length = in.read(buffer)) > 0) {
                out.write(buffer, 0, length);
            }
            in.close();
            out.close();

            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dFormat.format(txtDapp.getDate());
            String birth = dFormat.format(txtDob.getDate());
            pst.setString(1, date);
            pst.setString(2, txtFname.getText());
            pst.setString(3, txtLname.getText());
            pst.setString(4, txtCadd.getText());
            pst.setString(5, txtPadd.getText());
            pst.setString(6, birth);
            pst.setString(7, txtNationality.getText());
            pst.setString(8, txtTeleph.getText());
            pst.setString(9, txtMob.getText());
            pst.setString(10, txtEmail.getText());
            pst.setString(11, Gen);
            pst.setString(12, txtGovid.getText());
            pst.setString(13, txtClg1.getText());
            pst.setString(14, txtSem1.getText());
            pst.setString(15, txtStatus1.getText());
            pst.setString(16, txtDiv1.getText());
            pst.setString(17, txtBoard1.getText());
            pst.setString(18, txtSkill.getText());
            pst.setString(19, txtJob.getText());
            pst.setString(20, txtSalary.getText());
            pst.setBlob(21, imgg);
            pst.setString(22, label.getText());
            pst.execute();
            JOptionPane.showMessageDialog(this, "Successfully Saved", "Job-Chaiyo", JOptionPane.INFORMATION_MESSAGE);

            Clear();
        } catch (SQLException | FileNotFoundException ex) {
            Logger.getLogger(Reg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Reg.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSalaryKeyTyped
    String path = null;
    String docName = null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        if (evt.getSource() == jButton1) {
            int returnVal = fc.showSaveDialog(Reg.this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                path = file.getAbsolutePath();
                docName = file.getName();
                //This is where a real application would save the file.
                label.setText(file.getName());
                filepath = path;
            } else {
                // label.append("Save command cancelled by user.");
            }
            //label.setCaretPosition(label.getDocument().getLength());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttachFile;
    private javax.swing.JLabel btnGen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblimage;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radiofemale;
    private javax.swing.JTextField txtBoard1;
    private javax.swing.JTextField txtCadd;
    private javax.swing.JTextField txtClg1;
    private com.toedter.calendar.JDateChooser txtDapp;
    private javax.swing.JTextField txtDiv1;
    private com.toedter.calendar.JDateChooser txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtGovid;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMob;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPadd;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSem1;
    private javax.swing.JTextField txtSkill;
    private javax.swing.JTextField txtStatus1;
    private javax.swing.JTextField txtTeleph;
    // End of variables declaration//GEN-END:variables
}
